# Generated by Django 4.2 on 2025-10-21 12:28

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0007_ubysseyimage_description'),
        ('authors', '0021_alter_authorpage_options'),
        ('article', '0045_alter_articlepage_storystream_view_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('story_type', models.CharField(choices=[('event-report', 'Event report'), ('extended-report', 'Extended report'), ('public-service-announcement', 'Public Service Announcement'), ('opinion-essay', 'Opinion essay'), ('personal-essay', 'Personal essay'), ('review', 'Review'), ('guide', 'Guide'), ('explainer', 'Explainer'), ('profile', 'Profile')], max_length=50)),
                ('assigning_section', models.CharField(choices=[('news', 'News'), ('culture', 'Culture'), ('features', 'Features'), ('opinion', 'Opinion'), ('humour', 'Humour'), ('research', 'Research'), ('sports', 'Sports'), ('photo', 'Photo')], max_length=50)),
                ('summary', models.TextField()),
                ('article_file_folder', models.URLField()),
                ('manuscript', models.URLField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField()),
                ('target', models.DateField()),
                ('state', models.IntegerField(choices=[(1, 'Assigned'), (2, 'Editing'), (3, 'Ready'), (4, 'Published')], default=1)),
                ('article_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='article.articlepage', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisualAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.URLField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField()),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('state', models.IntegerField(choices=[(0, 'New'), (1, 'Assigned'), (2, 'Completed')], default=0)),
                ('request', models.TextField()),
                ('visual_type', models.CharField(choices=[('illustration', 'Illustration'), ('photo', 'Photo'), ('web-design', 'Webdesign')], max_length=50)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.ubysseyimage')),
                ('story_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visual_requests', to='content_tracker.storyassignment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisualAssignmentAssigneesOrderable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_assignments', to='authors.authorpage')),
                ('assignment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_assignees', to='content_tracker.visualassignment')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoryAssignmentAssigneesOrderable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_assignments', to='authors.authorpage')),
                ('assignment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_assignees', to='content_tracker.storyassignment')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
