# Generated by Django 4.2 on 2025-11-17 04:44

from django.db import migrations, models
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('content_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualassignment',
            name='image',
        ),
        migrations.AddField(
            model_name='visualassignment',
            name='visuals',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock(required=True))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='storyassignment',
            name='story_type',
            field=models.CharField(choices=[('event-report', 'Event report'), ('extended-report', 'Extended report'), ('public-service-announcement', 'Public Service Announcement'), ('opinion-essay', 'Opinion essay'), ('personal-essay', 'Personal essay'), ('review', 'Review'), ('guide', 'Guide'), ('explainer', 'Explainer'), ('profile', 'Profile'), ('q_&_a', 'Q&A'), ('humour', 'Humour')], max_length=50),
        ),
        migrations.AlterField(
            model_name='visualassignment',
            name='memo',
            field=models.URLField(verbose_name='Visual request form'),
        ),
        migrations.AlterField(
            model_name='visualassignment',
            name='visual_type',
            field=models.CharField(choices=[('illustration', 'Illustration'), ('photo', 'Photo'), ('web-design', 'Web design')], max_length=50),
        ),
    ]
