# Generated by Django 4.2 on 2025-11-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_tracker', '0002_remove_visualassignment_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualassignment',
            name='intended_use',
            field=models.CharField(choices=[('Print', 'For print'), ('Web', 'For web'), ('Web and Print', 'For Web and Print')], default='Unspecified', max_length=50),
        ),
    ]
