# Generated by Django 4.2 on 2026-01-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_tracker', '0003_visualassignment_intended_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualassignment',
            name='intended_use',
            field=models.CharField(choices=[('print', 'For print'), ('web', 'For web'), ('web & print', 'For web and print')], default='unspecified', max_length=50),
        ),
        migrations.AlterField(
            model_name='visualassignment',
            name='visual_type',
            field=models.CharField(choices=[('illustration', 'Illustration'), ('photo', 'Photo'), ('video', 'Video'), ('web-design', 'Web design')], max_length=50),
        ),
    ]
