# Generated by Django 4.2 on 2026-02-23 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0048_alter_standardarticlepage_content'),
        ('content_tracker', '0004_alter_visualassignment_intended_use_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyassignment',
            name='article_page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='article.articlepage'),
        ),
    ]
