# Generated by Django 4.2 on 2026-03-14 04:50

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content_tracker', '0005_alter_storyassignment_article_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyassignment',
            name='calendar_date',
            field=models.DateField(blank=True, help_text='Pin this assignment to a specific date on the editorial calendar.', null=True),
        ),
        migrations.AddField(
            model_name='storyassignment',
            name='is_podcast',
            field=models.BooleanField(default=False, verbose_name='Bound for podcast'),
        ),
        migrations.AddField(
            model_name='storyassignment',
            name='is_print',
            field=models.BooleanField(default=False, verbose_name='Bound for print'),
        ),
        migrations.AddField(
            model_name='storyassignment',
            name='memo',
            field=wagtail.fields.RichTextField(blank=True, help_text='Rich-text assignment brief for the reporter. Replaces external assignment memo documents.'),
        ),
        migrations.AddField(
            model_name='storyassignment',
            name='promotion_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storyassignment',
            name='promotion_ready',
            field=models.BooleanField(default=False, verbose_name='Ready for promotion'),
        ),
        migrations.AddField(
            model_name='storyassignment',
            name='promotion_type',
            field=models.CharField(blank=True, choices=[('social', 'Social media'), ('newsletter', 'Newsletter'), ('podcast', 'Podcast'), ('print', 'Print'), ('social+newsletter', 'Social + Newsletter')], max_length=50),
        ),
        migrations.AlterField(
            model_name='storyassignment',
            name='article_file_folder',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='storyassignment',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='storyassignment',
            name='manuscript',
            field=models.URLField(blank=True),
        ),
    ]
