# Generated by Django 4.2 on 2026-03-14 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('content_tracker', '0006_storyassignment_calendar_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyEditTaskState',
            fields=[
                ('taskstate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.taskstate')),
            ],
            options={
                'verbose_name': 'Copy edit task state',
                'verbose_name_plural': 'Copy edit task states',
            },
            bases=('wagtailcore.taskstate',),
        ),
        migrations.CreateModel(
            name='EngagementTaskState',
            fields=[
                ('taskstate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.taskstate')),
            ],
            options={
                'verbose_name': 'Engagement task state',
                'verbose_name_plural': 'Engagement task states',
            },
            bases=('wagtailcore.taskstate',),
        ),
        migrations.CreateModel(
            name='EngagementTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.task')),
                ('engagement_group', models.ForeignKey(blank=True, help_text='Users in this group are responsible for promoting stories.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.group')),
            ],
            options={
                'verbose_name': 'Engagement task',
                'verbose_name_plural': 'Engagement tasks',
            },
            bases=('wagtailcore.task',),
        ),
        migrations.CreateModel(
            name='CopyEditTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.task')),
                ('copy_editors_group', models.ForeignKey(blank=True, help_text='Users in this group can approve or request changes on copy edit tasks.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.group')),
            ],
            options={
                'verbose_name': 'Copy edit task',
                'verbose_name_plural': 'Copy edit tasks',
            },
            bases=('wagtailcore.task',),
        ),
    ]
