# Generated by Django 4.2 on 2026-03-15 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_tracker', '0007_add_copyedit_engagement_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyassignment',
            name='calendar_date',
        ),
    ]
