# Generated by Django 4.2 on 2026-01-13 17:22

from django.db import migrations, models
import django.db.models.deletion
import ubyssey.validators
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0048_alter_standardarticlepage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveBlogArticlePage',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.articlepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('article.articlepage',),
        ),
        migrations.CreateModel(
            name='LiveBlogUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('authors', wagtail.fields.StreamField([('author', wagtail.blocks.StructBlock([('author', wagtail.blocks.PageChooserBlock('authors.AuthorPage')), ('author_role', wagtail.blocks.CharBlock(max_length=250, required=False))]))], blank=True, null=True, use_json_field=True)),
                ('content', wagtail.fields.StreamField([('richtext', wagtail.blocks.RichTextBlock(help_text='Write your liveblog message contents here. See documentation: https://docs.wagtail.io/en/latest/editor_manual/new_pages/creating_body_content.html#rich-text-fields', label='Rich Text Block')), ('raw_html', wagtail.blocks.RawHTMLBlock(help_text="WARNING: DO NOT use this unless you really know what you're doing!", label='Raw HTML Block')), ('quote', wagtail.blocks.StructBlock([('content', wagtail.blocks.RichTextBlock(required=True)), ('style', wagtail.blocks.ChoiceBlock(choices=[('style_default', 'Default'), ('contrast', 'Contrast'), ('enlarged_quotation', 'Enlarged quotation'), ('block_quote', 'Block quote')])), ('source', wagtail.blocks.CharBlock(required=False)), ('audio', wagtail.documents.blocks.DocumentChooserBlock(help_text='Optional, file format: .m4a, .mp4, .mp, .wav, or .ogg', required=False)), ('images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('alt_text', wagtail.blocks.CharBlock(help_text='For accessibility to screen reader users, enter a description of this image. Included any relevant text inside the image.', max_length=255, required=False)), ('credit', wagtail.blocks.CharBlock(max_length=255, required=False))]), default=[], help_text='Optional!'))])), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('alt_text', wagtail.blocks.CharBlock(help_text='For accessibility to screen reader users, enter a description of this image. Included any relevant text inside the image.', max_length=255, required=False)), ('credit', wagtail.blocks.CharBlock(max_length=255, required=False)), ('caption', wagtail.blocks.CharBlock(max_length=255, required=False))])), ('storystream_item', wagtail.blocks.StructBlock([('article', wagtail.blocks.PageChooserBlock(page_type=['article.ArticlePage'])), ('storystream_overwrite', wagtail.blocks.StreamBlock([('featured_media', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('large-headline', 'Large headline'), ('featured', 'Featured (Featured media above, Headline below'), ('indent', 'Indent (Headline above, lede + featured media below')]))])), ('image', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('featured', 'Featured (image above, headline below)'), ('profile', 'Profile (headline left, tall cut out image with dropshadow right)'), ('indent', 'Indent (headline above, image below)')])), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('alt_text', wagtail.blocks.CharBlock(help_text='For accessibility to screen reader users, enter a description of this image. Included any relevant text inside the image.', max_length=255, required=False)), ('credit', wagtail.blocks.CharBlock(max_length=255, required=False))]))])), ('richtext', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('indent', 'Indent (headline above, lede + richtext below)')])), ('richtext', wagtail.blocks.RichTextBlock(required=True))])), ('no_attachment', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('indent', 'Indent (Headline above, lede below)')]))])), ('gallery', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('featured', 'Featured (gallery above, headline below)'), ('indent', 'Indent (headline above, gallery below)')])), ('images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('alt_text', wagtail.blocks.CharBlock(help_text='For accessibility to screen reader users, enter a description of this image. Included any relevant text inside the image.', max_length=255, required=False)), ('credit', wagtail.blocks.CharBlock(max_length=255, required=False))])))])), ('featured_video', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('featured', 'Featured (video above, headline below)'), ('indent', 'Indent (headline above, video below)')]))])), ('video', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('featured', 'Featured (video above, headline below)'), ('indent', 'Indent (headline above, video below)')])), ('video', wagtail.blocks.URLBlock(blank=False, default='', max_length=500, null=False, validators=[ubyssey.validators.validate_youtube_url]))])), ('embed', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('featured', 'Featured (embed above, headline below)'), ('indent', 'Indent (headline above, embed below)')])), ('raw_html', wagtail.blocks.RawHTMLBlock(help_text='You can use for this for embedding stuff from other sites (like youtube videos)', label='Raw HTML Block'))])), ('pdf', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('featured', 'Featured (embeded pdf above, headline below)'), ('indent', 'Indent (headline above, embeded pdf below)')])), ('pdf', wagtail.documents.blocks.DocumentChooserBlock(help_text='File format: .pdf', required=True))])), ('quote', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('featured', 'Featured (quote above with image as background, headline below)')])), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('alt_text', wagtail.blocks.CharBlock(help_text='For accessibility to screen reader users, enter a description of this image. Included any relevant text inside the image.', max_length=255, required=False)), ('credit', wagtail.blocks.CharBlock(max_length=255, required=False))])), ('quote', wagtail.blocks.TextBlock(required=True))]))], blank=True, max_num=1, required=False, use_json_field=True))]))], use_json_field=True)),
                ('room_name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
