# Generated by Django 4.2 on 2026-01-02 02:29

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0021_alter_authorpage_options'),
        ('article', '0047_alter_standardarticlepage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveBlogArticlePage',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.articlepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('article.articlepage',),
        ),
        migrations.CreateModel(
            name='LiveBlogUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_alias', models.CharField(blank=True, max_length=250, null=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('content', wagtail.fields.StreamField([('richtext', wagtail.blocks.RichTextBlock(help_text='Write your liveblog message contents here. See documentation: https://docs.wagtail.io/en/latest/editor_manual/new_pages/creating_body_content.html#rich-text-fields', label='Rich Text Block'))], use_json_field=True)),
                ('room_name', models.CharField(max_length=250)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authors.authorpage')),
            ],
        ),
    ]
