# Generated by Django 4.2 on 2026-03-02 13:38

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('liveblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveblogarticlepage',
            name='layout',
            field=models.CharField(default='default', max_length=100, verbose_name='Article Layout'),
        ),
        migrations.AddField(
            model_name='liveblogarticlepage',
            name='stage',
            field=wagtail.fields.StreamField([('header', wagtail.blocks.StructBlock([])), ('summary', wagtail.blocks.StructBlock([('richtext', wagtail.blocks.RichTextBlock(required=True))])), ('raw_html', wagtail.blocks.StructBlock([('raw_html', wagtail.blocks.RawHTMLBlock(required=True))]))], default=[{'type': 'header', 'value': {}}], use_json_field=True),
        ),
    ]
