# Generated by Django 4.2 on 2026-03-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveblog', '0002_liveblogarticlepage_layout_liveblogarticlepage_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveblogarticlepage',
            name='live_policy',
            field=models.CharField(default='auto-30m', help_text='Determines when the article is considered "Live".', max_length=100, verbose_name='Live policy'),
        ),
    ]
