# Generated by Django 5.2 on 2026-04-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveblog', '0003_liveblogarticlepage_live_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveblogupdate',
            name='publish_date',
            field=models.DateTimeField(blank=True, help_text="You can leave this blank (it will auto populate). It's only necessary for changing the order of the blocks", null=True),
        ),
    ]
