# Generated by Django 4.2 on 2024-08-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_description_alter_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hash',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
