# Generated by Django 4.2 on 2024-09-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=255, null=True),
        ),
    ]
