# Generated by Django 4.2 on 2025-05-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_address_alter_event_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hide_from_homepage',
            field=models.BooleanField(default=False, help_text='Check this to prevent the event from being featured on the homepage. This will NOT be overwritten, no matter the update mode.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='update_mode',
            field=models.IntegerField(default=0, help_text="Make sure you select 'Manual input', otherwise this event will be overwritten or deleted during the calendar's automatic daily update. Hide from homepage is NOT overwritten."),
        ),
    ]
