runtime: python39
entrypoint: gunicorn -b :$PORT --chdir ubyssey/ wsgi:application
instance_class: F4

default_expiration: "365d"

automatic_scaling:
  max_instances: 6

app_engine_apis: true

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: .*
  script: auto
  secure: always
