runtime: python39
entrypoint: gunicorn -b :$PORT --chdir ubyssey/ wsgi:application
instance_class: F4

default_expiration: "365d"

automatic_scaling:
  max_instances: 6

app_engine_apis: true

handlers:

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

# Archived pages

- url: /features/one-year-later-next
  static_files: static_archive/features/one-year-later-next/index.html
  upload: static_archive/features/one-year-later-next/index.html

- url: .*
  script: auto
  secure: always
