version: "3.7"
services:
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
      - 7900:7900 
    shm_size: 2gb
    
  selenium-edge:
    image: selenium/standalone-edge:latest
    ports:
      - 4445:4444 
      - 7901:7900 
    shm_size: 2gb

  selenium-firefox:
    image: selenium/standalone-firefox:latest
    ports:
      - 4446:4444 
      - 7902:7900 
    shm_size: 2gb

## Starts up mySQL server for ubyssey.ca and Dispatch
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ubyssey
      MYSQL_DATABASE: ubyssey
    ports:
      - "3307:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=ubyssey --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 20
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

## Starts up Django server for ubyssey.ca
  django:
    image: ubyssey/ubyssey.ca:latest
    volumes:
      - ..:/workspaces/mount
      - .:/workspaces/ubyssey.ca/tmp
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.development
    #ports:
      # # If you uncomment these, it will enable port TUNNELLING for the container
      # # Allocation of port tunnel can conflict with port forwarding! If you have issues make sure you're only using one or the other!
    #  - "8000:8000"
    #  - "4444:4444"
    depends_on:
      - db
    stdin_open: true
    tty: true
    
# ## Static filewatcher
  # filewatcher:
    # image: ubyssey/ubyssey-watcher:latest
    # volumes:
      # - ../ubyssey.ca/ubyssey/static/src:/src
    # depends_on:
      # - django
## 
  cache:
    platform: linux/x86_64
    image: memcached:1.6.10
    ports:
      - "11211:11211"
    depends_on:
      - django
    
volumes:
  database:
    external:
      name: ubyssey_db_volume
