# ARG must come before all FROM calls to be globally scoped
ARG ENVIRON
FROM python:3.8-buster
ARG ENVIRON
ENV PYTHONUNBUFFERED=1
ENV PORT=8000
EXPOSE 8000
COPY ./requirements.txt .
COPY ./requirements-prd.txt .
RUN if [ "$ENVIRON" = "production" ]; then pip install --requirement requirements-prd.txt; else pip install --requirement requirements.txt; fi
#ENTRYPOINT gunicorn --bind :$PORT --chdir ubyssey/ wsgi:application