version: "3.7"
services:

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ubyssey
      MYSQL_USER: ubyssey
      MYSQL_PASSWORD_FILE: /run/secrets/SQL_PASSWORD
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/SQL_PASSWORD
    secrets:
       - SQL_PASSWORD
    volumes:
      - ./mysql-data:/var/lib/mysql

  cache:
    image: memcached:1.6.10
    ports:
      - "11211:11211"

  django:
    image: ghcr.io/ubyssey/ubyssey.ca:${TAG}

    # The number of gunicorn workers below is derived from the number of CPU cores
    # on the VM using this formula: (2 x $num_cores) + 1, where $num_cores is 8.
    #
    # Total workers = (2 x 8) + 1 = 17
    #
    # We then further divide by the number of container replicas (4):
    #
    # Workers per replica = floor(17 / 4) = 4
    #
    # Ref: https://docs.gunicorn.org/en/latest/design.html#how-many-workers
    command: >
      bash -c "python manage.py migrate
      && gunicorn ubyssey.wsgi:application --workers=4 --bind 0.0.0.0:8000 --access-logfile - --error-logfile -"

    environment:
      SECRET_KEY_FILE: /run/secrets/DJANGO_SECRET_KEY
      SQL_HOST: mysql
      SQL_USER: root
      SQL_PASSWORD_FILE: /run/secrets/SQL_PASSWORD
      SQL_DATABASE: ubyssey
      GS_ACCESS_KEY_ID_FILE: /run/secrets/GS_ACCESS_KEY_ID
      GS_SECRET_ACCESS_KEY_FILE: /run/secrets/GS_SECRET_ACCESS_KEY
      STATIC_URL: https://storage.googleapis.com/ubyssey/static/
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/GOOGLE_APPLICATION_CREDENTIALS

    secrets:
      - DJANGO_SECRET_KEY
      - SQL_PASSWORD
      - GS_ACCESS_KEY_ID
      - GS_SECRET_ACCESS_KEY
      - GOOGLE_APPLICATION_CREDENTIALS

    expose:
      - 8000

    # Send container logs to Google Cloud Logging
    # Ref: https://docs.docker.com/engine/logging/drivers/gcplogs/
    logging:
      driver: gcplogs
    
    deploy:
      # Deploy 4 replicas of the Django app. This makes us more resilient to errors
      # that might cause a single container to crash momentarily.
      #
      # Ref: https://docs.docker.com/reference/compose-file/deploy/#replicas
      mode: replicated
      replicas: 4

      # Restart containers on failure up to a maximum of 10 times.
      # Ref: https://docs.docker.com/reference/compose-file/deploy/#restart_policy
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 120s

      # Update 2 containers at a time. This prevents downtime when releasing an update.
      # Ref: https://docs.docker.com/reference/compose-file/deploy/#update_config
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
  
    depends_on:
      - mysql
      - cache

  nginx:
    image: nginx:1.27
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/:/etc/nginx/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/letsencrypt-etc/:/etc/letsencrypt/:ro
    logging:
      driver: gcplogs
    depends_on:
      - django
  
  certbot:
    image: certbot/certbot:v4.0.0
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/letsencrypt-etc/:/etc/letsencrypt/:rw
      - ./certbot/letsencrypt-lib/:/var/lib/letsencrypt/:rw
    # Attempt to renew TLS certificate every 12 hours
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

secrets:
  DJANGO_SECRET_KEY:
    external: true
  SQL_PASSWORD:
    external: true
  GS_ACCESS_KEY_ID:
    external: true
  GS_SECRET_ACCESS_KEY:
    external: true
  GOOGLE_APPLICATION_CREDENTIALS:
    file: ./service-account.json
