version: "3.7"
services:

  db:
    platform: linux/x86_64
    image: mysql:8.0
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ubyssey
      MYSQL_DATABASE: ubyssey
    ports:
      - "3307:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=ubyssey --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 20

  django:
    image: ghcr.io/ubyssey/ubyssey.ca:staging-deploy
    command: >
      bash -c "python manage.py migrate
      && gunicorn ubyssey.wsgi:application --bind 0.0.0.0:8000"
    environment:
      STATIC_URL: https://storage.googleapis.com/ubyssey-staging/static/
      GS_ACCESS_KEY_ID: ${GS_ACCESS_KEY_ID}
      GS_SECRET_ACCESS_KEY: ${GS_SECRET_ACCESS_KEY}
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/GOOGLE_APPLICATION_CREDENTIALS
    secrets:
      - GOOGLE_APPLICATION_CREDENTIALS
    ports:
      - "8000:8000"
      - "4444:4444"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    stdin_open: true
    tty: true

secrets:
  GOOGLE_APPLICATION_CREDENTIALS:
    file: ./service-account.json

volumes:
  database:
