worker_processes 1;

events {
  worker_connections 1024;
  accept_mutex off;
}

http {
  upstream app_server {
    server django:8000 fail_timeout=0;
  }

  server {
    # If no Host match, close the connection to prevent host spoofing
    listen 80 default_server;
    return 444;
  }

  # Redirect HTTP requests to HTTPS server
  server {
    listen 80;
    client_max_body_size 4G;

    server_name staging.ubyssey.ca;

    keepalive_timeout 5;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot/;
    }
    location / {
        return 301 https://staging.ubyssey.ca$request_uri;
    }
  }

  # Handle staging.ubyssey.ca HTTPS traffic
  server {
    listen 443 default_server ssl;
    listen [::]:443 ssl;
    client_max_body_size 4G;

    server_name staging.ubyssey.ca;

    ssl_certificate /etc/letsencrypt/live/staging.ubyssey.ca/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/staging.ubyssey.ca/privkey.pem;

    # Handles websocket traffic which will always be at /ws/
    location /ws/ {
      proxy_pass http://app_server;

      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

      proxy_redirect off;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Host $server_name;
    }

    # Proxy all traffic to the Django app server
    location / {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_pass http://app_server;
    }
  }
}