worker_processes 1;

events {
  worker_connections 1024;
  accept_mutex off;
}

http {

  upstream app_server {
    server django:8000 fail_timeout=0;
  }

  server {
    # If no Hhst match, close the connection to prevent host spoofing
    listen 80 default_server;
    return 444;
  }

  # Redirect www.ubyssey.ca to ubyssey.ca
  server {
    listen 80;
    client_max_body_size 4G;

    server_name www.ubyssey.ca;

    # Redirect to ubyssey.ca using same HTTP scheme
    return 301 $scheme://ubyssey.ca$request_uri;
  }

  # Redirect HTTP requests to HTTPS server
  server {
    listen 80;
    client_max_body_size 4G;

    server_name ubyssey.ca;

    keepalive_timeout 5;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot/;
    }

    location / {
        return 301 https://ubyssey.ca$request_uri;
    }
  }

  # Redirect HTTPS requests for www.ubyssey.ca to ubyssey.ca
  server {
    listen 443 default_server ssl;
    listen [::]:443 ssl;
    client_max_body_size 4G;

    server_name www.ubyssey.ca;

    ssl_certificate /etc/letsencrypt/live/www.ubyssey.ca/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.ubyssey.ca/privkey.pem;
    
    location / {
        return 301 https://ubyssey.ca$request_uri;
    }
  }

  # Handle all HTTPS traffic
  server {
    listen 443 default_server ssl;
    listen [::]:443 ssl;
    client_max_body_size 4G;

    server_name ubyssey.ca;

    ssl_certificate /etc/letsencrypt/live/ubyssey.ca/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ubyssey.ca/privkey.pem;
    
    # Proxy all traffic to the Django app server
    location / {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_pass http://app_server;
    }
  }
}
