[tool.black]
line-length = 88
experimental-string-processing = true
target-version = ['py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
force-exclude = '''
/(
    .*migrations.*
    |.*config.*
    |.*__pycache__
)/
'''

[tool.isort]
profile = "black"
skip=['migrations', 'config', '__pycache__']