# Generated by Django 3.2.11 on 2023-05-30 23:47

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_authorpage_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorpage',
            name='linkIcons',
            field=wagtail.fields.StreamField([('raw_html', wagtail.blocks.RawHTMLBlock())], blank=True),
        ),
    ]
