# Generated by Django 3.2.11 on 2023-06-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_auto_20230618_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorpage',
            old_name='short_bio_descriptionn',
            new_name='short_bio_description',
        ),
    ]
