# Generated by Django 3.2.11 on 2023-05-31 00:17

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_authorpage_linkicons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorpage',
            name='linkIcons',
            field=wagtail.core.fields.StreamField([('richtext', wagtail.core.blocks.RichTextBlock())], blank=True),
        ),
    ]
