# Generated by Django 3.2.11 on 2023-06-21 10:30

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_alter_authorpage_short_bio_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorpage',
            name='bio_description',
            field=wagtail.fields.StreamField([('richtext', wagtail.blocks.RichTextBlock(help_text='Customise your bio here with links, bolds and italics!', label='Rich Text Block'))], blank=True, default=''),
        ),
    ]
