# Generated by Django 3.2.11 on 2023-05-31 00:24

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_alter_authorpage_linkicons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorpage',
            name='linkIcons',
            field=wagtail.fields.StreamField([('raw_html', wagtail.blocks.RawHTMLBlock())], blank=True),
        ),
    ]
