# Generated by Django 3.2.11 on 2023-06-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0009_alter_authorpage_bio_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorpage',
            name='bio_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='authorpage',
            name='short_bio_description',
            field=models.TextField(blank=True, default='', help_text='Please provide your title, year, program'),
        ),
    ]
