# Generated by Django 3.2.11 on 2023-06-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0010_pinnedarticlesorderable'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorpage',
            name='main_media_type',
            field=models.CharField(blank=True, choices=[('stories', 'Stories'), ('photos', 'Photos'), ('videos', 'Videos')], default='stories', max_length=20),
        ),
    ]
