# Generated by Django 3.2.11 on 2023-06-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0010_auto_20230626_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorpage',
            name='short_bio_description',
            field=models.TextField(blank=True, default='', help_text='Please provide your title, year and program'),
        ),
    ]
