# Generated by Django 3.2.11 on 2023-07-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0011_alter_authorpage_short_bio_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorpage',
            name='show_image',
            field=models.BooleanField(default=False, help_text="Do you want to display the author's image on the short bio in the article page?", verbose_name="Present author's image"),
        ),
    ]
