# Generated by Django 3.2.11 on 2023-06-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0011_authorpage_main_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorpage',
            name='main_media_type',
            field=models.CharField(choices=[('stories', 'Stories'), ('photos', 'Photos'), ('videos', 'Videos')], default='stories', max_length=20),
        ),
    ]
