# Generated by Django 3.2.11 on 2023-07-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0012_authorpage_show_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorpage',
            name='show_image',
        ),
        migrations.AddField(
            model_name='authorpage',
            name='display_image',
            field=models.BooleanField(default=False, help_text="Do you want to display the author's image on the short bio in the article page?", verbose_name="Present Author's Image"),
        ),
    ]
