# Generated by Django 3.2.11 on 2023-07-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0012_alter_authorpage_main_media_type'),
        ('authors', '0013_auto_20230704_0459'),
    ]

    operations = [
    ]
