# Generated by Django 3.2.11 on 2023-07-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0014_merge_20230718_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorpage',
            name='main_media_type',
            field=models.CharField(choices=[('articles', 'Articles'), ('photos', 'Photos'), ('videos', 'Videos')], default='stories', max_length=20),
        ),
    ]
