# Generated by Django 3.2.11 on 2023-08-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0015_alter_authorpage_main_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorpage',
            name='main_media_type',
            field=models.CharField(choices=[('articles', 'Articles'), ('photos', 'Photos'), ('videos', 'Videos')], default='articles', max_length=20),
        ),
    ]
