# Generated by Django 3.2.11 on 2023-08-16 05:48

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0016_alter_authorpage_main_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorpage',
            name='linkIcons',
            field=wagtail.fields.StreamField([('raw_html', wagtail.blocks.RawHTMLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='authorpage',
            name='links',
            field=wagtail.fields.StreamField([('url', wagtail.blocks.URLBlock(label='Url'))], blank=True, use_json_field=True),
        ),
    ]
