# Generated by Django 4.1 on 2024-05-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0017_auto_20230815_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorpage',
            name='short_bio_description',
            field=models.TextField(blank=True, default='', help_text='Please give a short bio in third person'),
        ),
    ]
