# Generated by Django 4.1 on 2024-06-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0018_authorpage_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorpage',
            name='short_bio_description',
            field=models.TextField(blank=True, default='', help_text='Please give a short bio in third person'),
        ),
    ]
