# Generated by Django 4.2 on 2025-01-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0019_alter_authorpage_short_bio_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorpage',
            name='main_media_type',
            field=models.CharField(choices=[('articles', 'Articles'), ('photos', 'Gallery'), ('videos', 'Videos'), ('visuals', 'Visual Bylines')], default='articles', max_length=20),
        ),
    ]
