# Generated by Django 4.2 on 2025-05-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0020_alter_authorpage_main_media_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorpage',
            options={'ordering': ['full_name'], 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
    ]
