# Generated by Django 4.2 on 2026-02-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0021_alter_authorpage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorpage',
            name='noindex',
            field=models.BooleanField(default=False, help_text='Warning: Only to be used when an article is requested to be unpublished, as per unpublishing policy. Should be FALSE in all but exceptional circumstances!', verbose_name="Add 'noindex' tag?"),
        ),
    ]
