# Generated by Django 4.2 on 2026-03-14 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authors', '0022_authorpage_noindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorpage',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link to the CMS user account for this author. Required for receiving assignment notifications.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_page', to=settings.AUTH_USER_MODEL),
        ),
    ]
