# Generated by Django 5.2 on 2026-09-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0023_authorpage_redesign_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorcontactorderable',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
