# Generated by Django 3.2.11 on 2023-05-20 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_ubysseyimage_legacy_pk'),
        ('section', '0003_sectionpage_use_parent_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner', to='images.ubysseyimage'),
        ),
    ]
