# Generated by Django 3.2.11 on 2023-05-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0004_sectionpage_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
