# Generated by Django 3.2.11 on 2023-05-23 22:21

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0005_sectionpage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='color',
            field=wagtail_color_panel.fields.ColorField(blank=True, max_length=7),
        ),
    ]
