# Generated by Django 3.2.11 on 2023-05-23 22:22

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0006_sectionpage_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='color',
            field=wagtail_color_panel.fields.ColorField(default='#0071c9', max_length=7),
        ),
    ]
