# Generated by Django 3.2.11 on 2023-05-23 22:48

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0008_auto_20230523_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='colour',
            field=wagtail_color_panel.fields.ColorField(default='#3490d6', max_length=7),
        ),
    ]
