# Generated by Django 3.2.11 on 2023-05-25 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_ubysseyimage_legacy_pk'),
        ('section', '0010_sectionpage_label_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysnippet',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoryBanner', to='images.ubysseyimage'),
        ),
    ]
