# Generated by Django 4.2 on 2025-02-11 10:56

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0016_sectionpage_top_stream_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sectionpage',
            name='top_stream',
            field=wagtail.fields.StreamField([('article_gatherer', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('section/objects/section_bulleted.html', 'Default'), ('section/objects/section_timeline.html', 'Timeline'), ('section/objects/section_horizontal.html', 'Horizontal'), ('section/objects/section_landing.html', 'Landing'), ('section/objects/minimal_grid.html', 'Minimal grid'), ('section/objects/blurb_with_timeline.html', 'Blurb with timeline'), ('section/objects/single_promo.html', 'Single (promo)'), ('section/objects/single_top-headline.html', 'Single (top headline)'), ('section/objects/single_top-headline_timeline.html', 'Single (top headline with timeline)')])), ('title', wagtail.blocks.CharBlock(help_text='Fill in to overwrite title', max_length=255, required=False)), ('description', wagtail.blocks.TextBlock(help_text='Fill in to overwrite description', required=False)), ('section', wagtail.blocks.PageChooserBlock(page_type=['section.SectionPage'], required=False)), ('category', wagtail.snippets.blocks.SnippetChooserBlock('section.CategorySnippet', required=False)), ('tag_slug', wagtail.blocks.CharBlock(help_text="Enter tag slug. For example for 'Christmas Movie' the slug would be 'christmas-movie'.", required=False)), ('hide_mobile', wagtail.blocks.BooleanBlock(default=False, help_text='If checked, will hide on small devices', required=False))])), ('landing', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('section/objects/section_bulleted.html', 'Default'), ('section/objects/section_timeline.html', 'Timeline'), ('section/objects/section_horizontal.html', 'Horizontal'), ('section/objects/section_landing.html', 'Landing'), ('section/objects/minimal_grid.html', 'Minimal grid'), ('section/objects/blurb_with_timeline.html', 'Blurb with timeline'), ('section/objects/single_promo.html', 'Single (promo)'), ('section/objects/single_top-headline.html', 'Single (top headline)'), ('section/objects/single_top-headline_timeline.html', 'Single (top headline with timeline)')])), ('landing', wagtail.blocks.PageChooserBlock(page_type=['specialfeaturelanding.SpecialLandingPage']))])), ('article_manual', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('section/objects/section_bulleted.html', 'Default'), ('section/objects/section_timeline.html', 'Timeline'), ('section/objects/section_horizontal.html', 'Horizontal'), ('section/objects/section_landing.html', 'Landing'), ('section/objects/minimal_grid.html', 'Minimal grid'), ('section/objects/blurb_with_timeline.html', 'Blurb with timeline'), ('section/objects/single_promo.html', 'Single (promo)'), ('section/objects/single_top-headline.html', 'Single (top headline)'), ('section/objects/single_top-headline_timeline.html', 'Single (top headline with timeline)')])), ('title', wagtail.blocks.CharBlock(max_length=255, required=False)), ('description', wagtail.blocks.TextBlock(required=False)), ('link', wagtail.blocks.URLBlock(required=False)), ('articles', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(page_type=['article.ArticlePage'])))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
