# Generated by Django 4.2 on 2025-02-18 10:18

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0017_alter_sectionpage_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('sectionpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='section.sectionpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('section.sectionpage',),
        ),
        migrations.RemoveField(
            model_name='categorymenuitem',
            name='category',
        ),
        migrations.AlterField(
            model_name='sectionpage',
            name='top_stream',
            field=wagtail.fields.StreamField([('article_gatherer', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('section/objects/section_bulleted.html', 'Default'), ('section/objects/section_timeline.html', 'Timeline'), ('section/objects/section_horizontal.html', 'Horizontal'), ('section/objects/section_landing.html', 'Landing'), ('section/objects/minimal_grid.html', 'Minimal grid'), ('section/objects/blurb_with_timeline.html', 'Blurb with timeline'), ('section/objects/single_promo.html', 'Single (promo)'), ('section/objects/single_top-headline.html', 'Single (top headline)'), ('section/objects/single_top-headline_timeline.html', 'Single (top headline with timeline)')])), ('title', wagtail.blocks.CharBlock(help_text='Fill in to overwrite title', max_length=255, required=False)), ('description', wagtail.blocks.RichTextBlock(help_text='Fill in to overwrite description', required=False)), ('section', wagtail.blocks.PageChooserBlock(page_type=['section.SectionPage'], required=False)), ('category', wagtail.blocks.PageChooserBlock(page_type=['section.CategoryPage'], required=False)), ('tag_slug', wagtail.blocks.CharBlock(help_text="Enter tag slug. For example for 'Christmas Movie' the slug would be 'christmas-movie'.", required=False)), ('hide_mobile', wagtail.blocks.BooleanBlock(default=False, help_text='If checked, will hide on small devices', required=False))])), ('landing', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('section/objects/section_bulleted.html', 'Default'), ('section/objects/section_timeline.html', 'Timeline'), ('section/objects/section_horizontal.html', 'Horizontal'), ('section/objects/section_landing.html', 'Landing'), ('section/objects/minimal_grid.html', 'Minimal grid'), ('section/objects/blurb_with_timeline.html', 'Blurb with timeline'), ('section/objects/single_promo.html', 'Single (promo)'), ('section/objects/single_top-headline.html', 'Single (top headline)'), ('section/objects/single_top-headline_timeline.html', 'Single (top headline with timeline)')])), ('landing', wagtail.blocks.PageChooserBlock(page_type=['specialfeaturelanding.SpecialLandingPage']))])), ('article_manual', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('section/objects/section_bulleted.html', 'Default'), ('section/objects/section_timeline.html', 'Timeline'), ('section/objects/section_horizontal.html', 'Horizontal'), ('section/objects/section_landing.html', 'Landing'), ('section/objects/minimal_grid.html', 'Minimal grid'), ('section/objects/blurb_with_timeline.html', 'Blurb with timeline'), ('section/objects/single_promo.html', 'Single (promo)'), ('section/objects/single_top-headline.html', 'Single (top headline)'), ('section/objects/single_top-headline_timeline.html', 'Single (top headline with timeline)')])), ('title', wagtail.blocks.CharBlock(max_length=255, required=False)), ('description', wagtail.blocks.RichTextBlock(required=False)), ('link', wagtail.blocks.URLBlock(required=False)), ('articles', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(page_type=['article.ArticlePage']), required=False))])), ('article_gatherer_with_pinned', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('section/objects/elections_race_timeline_with_candidates.html', 'Default')])), ('title', wagtail.blocks.CharBlock(help_text='Fill in to overwrite title', max_length=255, required=False)), ('description', wagtail.blocks.RichTextBlock(help_text='Fill in to overwrite description', required=False)), ('section', wagtail.blocks.PageChooserBlock(page_type=['section.SectionPage'], required=False)), ('category', wagtail.blocks.PageChooserBlock(page_type=['section.CategoryPage'], required=False)), ('tag_slug', wagtail.blocks.CharBlock(help_text="Enter tag slug. For example for 'Christmas Movie' the slug would be 'christmas-movie'.", required=False)), ('hide_mobile', wagtail.blocks.BooleanBlock(default=False, help_text='If checked, will hide on small devices', required=False)), ('pinned', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(page_type=['article.ArticlePage']), required=False))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='categorymenuitem',
            name='category_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.categorypage'),
        ),
    ]
