# Generated by Django 4.2 on 2025-02-21 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0016_alter_sectionpage_sidebar_stream'),
        ('section', '0019_alter_sectionpage_sidebar_stream'),
    ]

    operations = [
    ]
