# Generated by Django 5.2 on 2026-07-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0025_alter_sectionpage_top_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='beat',
            field=models.BooleanField(default=False),
        ),
    ]
