# Generated by Django 5.2 on 2026-09-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0028_sectionpage_redesign_cms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionredesignfeaturedarticle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
