# Generated by Django 3.2.11 on 2023-03-25 01:39

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_auto_20220707_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adslot',
            name='dfp',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ad Unit Name (AKA "DFP")'),
        ),
        migrations.CreateModel(
            name='ArticleInlinePlacementOrderable',
            fields=[
                ('adplacementorderable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ads.adplacementorderable')),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_inline_placements', to='ads.adtagsettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('ads.adplacementorderable',),
        ),
    ]
