# Generated by Django 3.2.11 on 2023-05-12 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_articlepage_noindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Pinned to Homepage?'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='pinned_timeout',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
