# Generated by Django 3.2.11 on 2023-06-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_articlepage_magazine_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MagazineTagOrderable',
        ),
    ]
