# Generated by Django 3.2.11 on 2023-05-17 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_alter_articlepage_pinned_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='pinned_timeout',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
