# Generated by Django 3.2.11 on 2023-08-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_alter_articlepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='posted_to_mastodon',
            field=models.BooleanField(default=False),
        ),
    ]
