# Generated by Django 3.2.11 on 2023-05-18 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_alter_articlepage_pinned_timeout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='pinned_timeout',
        ),
    ]
