# Generated by Django 3.2.11 on 2023-07-10 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_delete_magazinetagorderable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='magazine_tag',
        ),
    ]
