# Generated by Django 3.2.11 on 2023-05-18 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_remove_articlepage_pinned_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='pinned_end_gte',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='pinned_start_lte',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
