# Generated by Django 3.2.11 on 2023-07-10 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_remove_articlepage_magazine_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MagazineTagSnippet',
        ),
    ]
