# Generated by Django 4.1 on 2024-04-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_alter_articlepage_content'),
        ('article', '0022_alter_articlepagetag_tag'),
    ]

    operations = [
    ]
