# Generated by Django 3.2.11 on 2023-05-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_auto_20230518_0524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepage',
            old_name='pinned_end_gte',
            new_name='pinned_end',
        ),
        migrations.RenameField(
            model_name='articlepage',
            old_name='pinned_start_lte',
            new_name='pinned_start',
        ),
    ]
