# Generated by Django 4.1 on 2024-06-18 05:50

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('article', '0025_alter_articlepage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryArticlePageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'primary article tag',
                'verbose_name_plural': 'primary article tags',
            },
        ),
        migrations.AddField(
            model_name='articlepage',
            name='primary_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='article.PrimaryArticlePageTag', to='taggit.Tag', verbose_name='Primary Tags'),
        ),
        migrations.AddField(
            model_name='primaryarticlepagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_tagged_items', to='article.articlepage'),
        ),
        migrations.AddField(
            model_name='primaryarticlepagetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
    ]
