# Generated by Django 4.1 on 2024-05-18 02:34

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0025_remove_articlepage_fw_optional_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='disclaimer',
            field=wagtail.fields.RichTextField(blank=True, default='', help_text='Used for Opinion articles or when corrections are made'),
        ),
    ]
