# Generated by Django 4.1 on 2024-07-11 05:43

from django.db import migrations, models
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('article', '0026_remove_articlepage_fw_optional_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='filter_by_tags',
            field=models.BooleanField(default=False, help_text='Check this box if you want to filter suggested articles by tag.'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='primary_tag_slug',
            field=models.CharField(blank=True, default='', help_text="Enter the slug of the tag to be used for linking at the end of the article. For example, the slug of the tag 'blue chip' is 'blue-chip'.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='tag_page_link',
            field=models.BooleanField(default=False, help_text='Check this box if you want to add a link to the tag page.'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text="Tags entered here will be listed in the tag page at '/tag/tag-name'", through='article.ArticlePageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
