# Generated by Django 4.1 on 2024-06-18 06:01

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('article', '0026_primaryarticlepagetag_articlepage_primary_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='primary_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Only input the most important tag in this box. Remaining tags should be input in the Tags field.', through='article.PrimaryArticlePageTag', to='taggit.Tag', verbose_name='Primary Tags'),
        ),
    ]
