# Generated by Django 4.2 on 2024-08-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0027_articlepage_filter_by_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text='Displayed below the title', max_length=255, verbose_name='Subtitle (Optional)'),
        ),
    ]
