# Generated by Django 4.1 on 2024-06-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0027_alter_articlepage_primary_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='tag_page',
            field=models.BooleanField(default=False, help_text='Check this box if you want to add a link to the tag page'),
        ),
    ]
