# Generated by Django 4.1 on 2024-06-18 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0028_articlepage_tag_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepage',
            old_name='tag_page',
            new_name='tag_page_link',
        ),
    ]
