# Generated by Django 4.1 on 2024-06-19 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0029_rename_tag_page_articlepage_tag_page_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='primary_tags',
        ),
    ]
