# Generated by Django 4.2 on 2025-02-18 10:18

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('section', '0018_categorypage_remove_categorymenuitem_category_and_more'),
        ('article', '0030_alter_articlepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='category_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.categorypage'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='filter_by_tags',
            field=models.BooleanField(default=False, help_text='CHECK THIS to fill the suggested bar with other articles in this section that are also tagged with the primary tag.', verbose_name='Use Primary Tag for Suggested Bar'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='tag_page_link',
            field=models.BooleanField(default=False, help_text='Check this if you want to add a link to the primary tag page at the end of the article.', verbose_name='Link to Primary Tag at the End of the Article'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text="ADD 'Top stories' IF YOU WANT IT TO GO ON TOP STORIES LIST. Tags entered here will be listed in the tag page with the format 'https://ubyssey.ca/tag/top-stories/'.", through='article.ArticlePageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
