# Generated by Django 4.1 on 2024-06-19 06:41

from django.db import migrations, models
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('article', '0030_remove_articlepage_primary_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='tag_page_link',
            field=models.BooleanField(default=False, help_text='Check this box if you want to add a link to the tag page.'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Input the most relevant tags for this article first.', through='article.ArticlePageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
