# Generated by Django 4.1 on 2024-06-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0031_alter_articlepage_tag_page_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='filter_by_tags',
            field=models.BooleanField(default=False, help_text='Check this box if you want to filter suggested articles by tag.'),
        ),
    ]
