# Generated by Django 4.2 on 2025-02-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0031_articlepage_category_page_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='articlepage',
            name='article_art_categor_64ad02_idx',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='category',
        ),
        migrations.AddIndex(
            model_name='articlepage',
            index=models.Index(fields=['category_page'], name='article_art_categor_2f4484_idx'),
        ),
    ]
