# Generated by Django 4.2 on 2025-05-30 04:09

from django.db import migrations, models
import ubyssey.validators
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0035_remove_connectedarticleorderable_article_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlefeaturedmediaorderable',
            name='video',
            field=models.URLField(blank=True, default='', max_length=500, null=True, validators=[ubyssey.validators.validate_youtube_url]),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='storystream_view',
            field=wagtail.fields.StreamField([('featured_media', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('large-headline', 'Large headline (Large headline left, small featured media right)'), ('featured', 'Featured (Featured media above, Headline below'), ('indent', 'Indent (Headline above, lede + featured media below')]))])), ('image', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('featured', 'Featured (image above, headline below)'), ('profile', 'Profile (headline left, tall cut out image with dropshadow right)'), ('indent', 'Indent (headline above, image below)')])), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('alt_text', wagtail.blocks.CharBlock(help_text='For accessibility to screen reader users, enter a description of this image. Included any relevant text inside the image.', max_length=255, required=False))]))])), ('richtext', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('indent', 'Indent (headline above, lede + richtext below)')])), ('richtext', wagtail.blocks.RichTextBlock(required=True))])), ('no_attachment', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('indent', 'Indent (Headline above, lede below)')]))])), ('gallery', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('featured', 'Featured (gallery above, headline below)'), ('indent', 'Indent (headline above, gallery below)')])), ('images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('alt_text', wagtail.blocks.CharBlock(help_text='For accessibility to screen reader users, enter a description of this image. Included any relevant text inside the image.', max_length=255, required=False))])))])), ('featured_video', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('featured', 'Featured (video above, headline below)'), ('indent', 'Indent (headline above, video below)')]))])), ('video', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('featured', 'Featured (video above, headline below)'), ('indent', 'Indent (headline above, video below)')])), ('video', wagtail.blocks.URLBlock(blank=False, default='', max_length=500, null=False, validators=[ubyssey.validators.validate_youtube_url]))])), ('embed', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('featured', 'Featured (embed above, headline below)'), ('indent', 'Indent (headline above, embed below)')])), ('raw_html', wagtail.blocks.RawHTMLBlock(help_text='You can use for this for embedding stuff from other sites (like youtube videos)', label='Raw HTML Block'))])), ('pdf', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('featured', 'Featured (embeded pdf above, headline below)'), ('indent', 'Indent (headline above, embeded pdf below)')])), ('pdf', wagtail.documents.blocks.DocumentChooserBlock(help_text='File format: .pdf', required=True))])), ('quote', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('featured', 'Featured (quote above with image as background, headline below)')])), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('alt_text', wagtail.blocks.CharBlock(help_text='For accessibility to screen reader users, enter a description of this image. Included any relevant text inside the image.', max_length=255, required=False))])), ('quote', wagtail.blocks.TextBlock(required=True))]))], use_json_field=True),
        ),
    ]
