# Generated by Django 4.2 on 2025-06-03 11:11

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
import wagtail.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('taggit', '0005_auto_20220424_2025'),
        ('article', '0036_alter_articlefeaturedmediaorderable_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
                ('description', wagtail.fields.RichTextField(blank=True, default='', help_text='Give an overview of the topic. Link densely to our coverage.')),
                ('info_updated_at', models.DateTimeField(blank=True, help_text='Delete before saving ', null=True, verbose_name='Description Updated Date/Time')),
                ('listed', models.BooleanField(default=False, help_text='Listed topics are displayed at the end of tagged articles')),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, help_text='Stores the last time an article tagged with this topic was published', null=True, verbose_name='Last used at')),
                ('tagged_articles_count', models.IntegerField(default=0, editable=False)),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
            ],
            options={
                'verbose_name': 'Article topic',
                'verbose_name_plural': 'Article topics',
            },
            bases=(wagtail.models.PreviewableMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text="ADD 'Top stories' IF YOU WANT IT TO GO ON TOP STORIES LIST.", through='article.ArticlePageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='TaggedArticlePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_articles', to='article.articlepage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_articles', to='article.articletopic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='articlepage',
            name='topics',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text="ADD 'Top stories' IF YOU WANT IT TO GO ON TOP STORIES LIST.", through='article.TaggedArticlePage', to='article.ArticleTopic', verbose_name='Topics'),
        ),
    ]
