# Generated by Django 4.2 on 2025-08-06 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0038_standardarticlepage_remove_articlepage_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='db_template',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='disclaimer',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='fw_about_this_article',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='fw_above_cut_lede',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='fw_alternate_title',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='header_layout',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='legacy_revision_number',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='legacy_template',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='legacy_template_data',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='show_timeline',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='timeline',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='timeline_date',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='use_default_template',
        ),
    ]
