# Generated by Django 4.2 on 2025-08-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0039_remove_articlepage_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standardarticlepage',
            old_name='content_sap',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='standardarticlepage',
            old_name='db_template_sap',
            new_name='db_template',
        ),
        migrations.RenameField(
            model_name='standardarticlepage',
            old_name='disclaimer_sap',
            new_name='disclaimer',
        ),
        migrations.RenameField(
            model_name='standardarticlepage',
            old_name='fw_alternate_title_sap',
            new_name='fw_alternate_title',
        ),
        migrations.RenameField(
            model_name='standardarticlepage',
            old_name='header_layout_sap',
            new_name='header_layout',
        ),
        migrations.RenameField(
            model_name='standardarticlepage',
            old_name='layout_sap',
            new_name='layout',
        ),
        migrations.RenameField(
            model_name='standardarticlepage',
            old_name='legacy_revision_number_sap',
            new_name='legacy_revision_number',
        ),
        migrations.RenameField(
            model_name='standardarticlepage',
            old_name='legacy_template_sap',
            new_name='legacy_template',
        ),
        migrations.RenameField(
            model_name='standardarticlepage',
            old_name='legacy_template_data_sap',
            new_name='legacy_template_data',
        ),
        migrations.RenameField(
            model_name='standardarticlepage',
            old_name='subtitle_sap',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='standardarticlepage',
            old_name='use_default_template_sap',
            new_name='use_default_template',
        ),
    ]
