# Generated by Django 4.2 on 2025-08-08 10:43

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0040_rename_content_sap_standardarticlepage_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardarticlepage',
            name='header',
            field=wagtail.fields.StreamField([('standard_header', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('alt_text', wagtail.blocks.CharBlock(help_text='For accessibility to screen reader users, enter a description of this image. Included any relevant text inside the image.', max_length=255, required=False))]))), ('layout', wagtail.blocks.ChoiceBlock(choices=[('no-banner', 'No Banner'), ('no-image', 'No Image'), ('right-image', 'Right Image'), ('bottom-image', 'Bottom Image'), ('left-image', 'Left Image'), ('top-image', 'Top Image'), ('banner-image', 'Banner Image'), ('video-banner', 'Video banner')]))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
