# Generated by Django 4.2 on 2025-08-10 08:20

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0041_standardarticlepage_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardarticlepage',
            name='header',
            field=wagtail.fields.StreamField([('standard_header', wagtail.blocks.StructBlock([('layout', wagtail.blocks.ChoiceBlock(choices=[('no-image', 'No Image'), ('right-image', 'Right Image'), ('bottom-image', 'Bottom Image'), ('left-image', 'Left Image'), ('top-image', 'Top Image'), ('banner-image', 'Banner Image')])), ('title', wagtail.blocks.CharBlock(help_text='When there is a "special feature" or full-width style article, sometimes we would like to override the title as it render in the template', label='Alternate title', max_length=255, required=False)), ('subtitle', wagtail.blocks.CharBlock(help_text='Displayed below the title', max_length=255, required=False)), ('above_cut_lede', wagtail.blocks.RichTextBlock(help_text='Articles that use a special header/banner often contain a second lede/abstract summary ', required=False))])), ('standard_header_with_youtube_video', wagtail.blocks.StructBlock([('layout', wagtail.blocks.ChoiceBlock(choices=[('bottom-image', 'Bottom Image'), ('top-image', 'Top Image'), ('video-banner', 'Video banner')])), ('title', wagtail.blocks.CharBlock(help_text='When there is a "special feature" or full-width style article, sometimes we would like to override the title as it render in the template', label='Alternate title', max_length=255, required=False)), ('subtitle', wagtail.blocks.CharBlock(help_text='Displayed below the title', max_length=255, required=False)), ('above_cut_lede', wagtail.blocks.RichTextBlock(help_text='Articles that use a special header/banner often contain a second lede/abstract summary ', required=False)), ('youtube_url', wagtail.blocks.URLBlock(required=True))]))], blank=True, default=[{'type': 'standard_header', 'value': {'above_cut_lede': '', 'layout': 'bottom-image', 'subtitle': '', 'title': ''}}], null=True, use_json_field=True),
        ),
    ]
