# Generated by Django 5.2 on 2026-03-24 19:54

import images.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0048_alter_standardarticlepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletopic',
            name='relevance_score',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
