# Generated by Django 5.2 on 2026-03-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0049_articletopic_relevance_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleauthorsorderable',
            name='author_alias',
            field=models.CharField(blank=True, default=None, help_text='To be used for humour articles only. Overwrites the authors name.', max_length=255, null=True),
        ),
    ]
