# Generated by Django 4.2 on 2026-03-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0049_tiptaparticlepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiptaparticlepage',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
