# Generated by Django 5.2 on 2026-06-08 18:22

import json
import re

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


IMAGE_KEYS = {"image"}
DOCUMENT_KEYS = {"audio", "document", "pdf", "video"}


def media_id(value):
    if isinstance(value, int):
        return value
    if isinstance(value, str) and value.isdigit():
        return int(value)
    return None


def collect_richtext_media(value, image_ids, document_ids):
    for tag in re.findall(r"<[^>]+>", value):
        id_match = re.search(r'id=["\'](\d+)["\']', tag)
        if not id_match:
            continue
        if re.search(r'(?:embedtype|linktype)=["\']image["\']', tag):
            image_ids.append(int(id_match.group(1)))
        if re.search(r'(?:embedtype|linktype)=["\']document["\']', tag):
            document_ids.append(int(id_match.group(1)))


def collect_media(value, image_ids, document_ids):
    if value is None:
        return

    raw = getattr(value, "raw_data", None) or getattr(value, "stream_data", None)
    if raw is not None:
        value = raw

    if isinstance(value, str):
        try:
            value = json.loads(value)
        except ValueError:
            collect_richtext_media(value, image_ids, document_ids)
            return

    if isinstance(value, list):
        for item in value:
            collect_media(item, image_ids, document_ids)
        return

    if not isinstance(value, dict):
        return

    for key, item in value.items():
        if key in IMAGE_KEYS:
            found = media_id(item)
            if found:
                image_ids.append(found)
        elif key in DOCUMENT_KEYS:
            found = media_id(item)
            if found:
                document_ids.append(found)
        collect_media(item, image_ids, document_ids)


def backfill_article_media(apps, schema_editor):
    ArticleMedia = apps.get_model("article", "ArticleMediaOrderable")
    Image = apps.get_model("images", "UbysseyImage")
    Document = apps.get_model("wagtaildocs", "Document")

    pairs = {}

    def remember(article_id, image_id=None, document_id=None):
        if not article_id or not (image_id or document_id):
            return
        pair = (image_id, document_id)
        bucket = pairs.setdefault(article_id, [])
        if pair not in bucket:
            bucket.append(pair)

    for model_name, fields in [
        ("ArticlePage", ["storystream_view"]),
        ("StandardArticlePage", ["header", "content"]),
        ("SpecialArticleLikePage", ["right_column_content"]),
        ("StandardArticlePageWithRightColumn", ["right_column_content"]),
    ]:
        Model = apps.get_model("article", model_name)
        for page in Model.objects.all().only(*fields).iterator():
            image_ids = []
            document_ids = []
            for field in fields:
                collect_media(getattr(page, field, None), image_ids, document_ids)
            for image_id in image_ids:
                remember(page.pk, image_id=image_id)
            for document_id in document_ids:
                remember(page.pk, document_id=document_id)

    valid_images = set(Image.objects.filter(id__in={p[0] for items in pairs.values() for p in items if p[0]}).values_list("id", flat=True))
    valid_documents = set(Document.objects.filter(id__in={p[1] for items in pairs.values() for p in items if p[1]}).values_list("id", flat=True))
    rows = []

    for article_id, items in pairs.items():
        sort_order = 0
        for image_id, document_id in items:
            if image_id and image_id not in valid_images:
                continue
            if document_id and document_id not in valid_documents:
                continue
            rows.append(ArticleMedia(article_page_id=article_id, image_id=image_id, document_id=document_id, sort_order=sort_order))
            sort_order += 1

    ArticleMedia.objects.bulk_create(rows, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0049_alter_standardarticlepage_content_and_more'),
        ('images', '0007_ubysseyimage_description'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMediaOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('article_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_media', to='article.articlepage')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.ubysseyimage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RunPython(backfill_article_media, migrations.RunPython.noop),
    ]
