# Generated by Django 5.2 on 2026-04-09 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0050_articleauthorsorderable_author_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticArticlePage',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.articlepage')),
                ('static_file', models.URLField(help_text='A link to the storage bucket where articles from our archive are stored as static files.')),
            ],
            options={
                'abstract': False,
            },
            bases=('article.articlepage',),
        ),
        migrations.AlterField(
            model_name='articleauthorsorderable',
            name='author_alias',
            field=models.CharField(blank=True, default=None, help_text="To be used for humour articles only. Overwrites the author's name.", max_length=255, null=True),
        ),
    ]
