# Generated by Django 4.2 on 2026-03-09 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0050_tiptaparticlepage_body_to_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiptaparticlepage',
            name='lede',
        ),
    ]
