# Generated by Django 5.2 on 2026-06-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0050_article_media'),
        ('article', '0052_alter_articlepage_storystream_view_and_more'),
    ]

    operations = [
    ]
