# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0054_alter_standardarticlepage_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardarticlepage",
            name="stove_comment_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                editable=False,
                help_text="Private Stove comment metadata. Not rendered to readers.",
            ),
        ),
    ]
