# Generated by Django 5.2 on 2026-06-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0054_alter_standardarticlepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text="The targeted deadline for a writer's initial submission of the piece.", null=True, verbose_name='Deadline'),
        ),
    ]
