# Generated by Django 5.2 on 2026-07-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0055_articlepage_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='article_status',
            field=models.IntegerField(choices=[(1, 'Assigned'), (2, 'Filed'), (3, 'Editing'), (4, 'Copy'), (5, 'Ready'), (6, 'Published')], default=1),
        ),
    ]
