# Generated by Django 5.2 on 2026-06-30 18:39

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('article', '0055_standardarticlepage_stove_comment_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standardarticlepage',
            old_name='stove_comment_data',
            new_name='editor_article_version',
        ),
    ]