# Generated by Django 5.2 on 2026-07-18 06:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0057_richtext_display_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardarticlepage',
            name='header',
            field=wagtail.fields.StreamField([('standard_header', 10), ('standard_header_with_youtube_video', 13)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('no-image', 'No Image'), ('right-image', 'Right Image'), ('bottom-image', 'Bottom Image'), ('left-image', 'Left Image'), ('top-image', 'Top Image'), ('banner-image', 'Banner Image'), ('banner-image--full-height--headline-left--headline-bottom', 'Full Height Banner Image (Bottom, Left Headline)'), ('banner-image--full-height--headline-right--headline-bottom', 'Full Height Banner Image (Bottom, Right Headline)'), ('banner-image--full-height--headline-left--headline-top--headline-one-third-width', 'Full Height Banner Image (Top, Left Headline)'), ('banner-image--full-height--headline-right--headline-top--headline-one-third-width', 'Full Height Banner Image (Top, Right Headline)'), ('banner-image--full-height--headline-left--headline-mid--headline-one-third-width', 'Full Height Banner Image (Mid, Left Headline)'), ('banner-image--full-height--headline-right--headline-mid--headline-one-third-width', 'Full Height Banner Image (Mid, Right Headline)'), ('timeless-meta-page-banner', 'Timeless Meta Page Banner'), ('communications-page-banner', 'Communications Page Banner')]}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'When there is a "special feature" or full-width style article, sometimes we would like to override the title as it render in the template', 'label': 'Alternate title', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Displayed below the title', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Articles that use a special header/banner often contain a second lede/abstract summary ', 'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'For accessibility to screen reader users, enter a description of this image. Included any relevant text inside the image.', 'max_length': 255, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 7: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('image', 4), ('alt_text', 5), ('credit', 6), ('caption', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'default': [], 'help_text': 'ONLY SET THIS IF YOU WANT SEPARATE IMAGES FOR THE HEADER AND THE ARTICLE LISTING WITHIN SECTION PAGES.', 'max_num': 1}), 10: ('wagtail.blocks.StructBlock', [[('layout', 0), ('title', 1), ('subtitle', 2), ('above_cut_lede', 3), ('overwrite_image', 9)]], {}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bottom-image', 'Bottom Image'), ('top-image', 'Top Image'), ('video-banner', 'Video banner')]}), 12: ('wagtail.blocks.URLBlock', (), {'required': True}), 13: ('wagtail.blocks.StructBlock', [[('layout', 11), ('title', 1), ('subtitle', 2), ('above_cut_lede', 3), ('overwrite_image', 9), ('youtube_url', 12)]], {})}, default=[{'type': 'standard_header', 'value': {'above_cut_lede': '', 'layout': 'bottom-image', 'subtitle': '', 'title': ''}}], null=True),
        ),
    ]
