# Generated by Django 5.2 on 2026-07-20 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0056_articlepage_article_status'),
        ('article', '0058_restore_plain_text_titles'),
    ]

    operations = [
    ]
