# Generated by Django 5.2 on 2026-08-10 15:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0059_merge_20260719_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='assignment_memo',
            field=wagtail.fields.RichTextField(blank=True, default='', help_text='Advice from a section editor about how to approach a story', verbose_name='Assignment Memorandum'),
        ),
    ]
