# Generated by Django 5.2 on 2026-08-11 01:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0060_articlepage_assignment_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='ethics_notes',
            field=wagtail.fields.RichTextField(blank=True, default='', help_text='Advice from a section editor about the ethics of a story', verbose_name='Ethics Notes'),
        ),
    ]
