# Generated by Django 5.2 on 2026-08-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0061_articlepage_ethics_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='assignment_folder',
            field=models.URLField(blank=True, help_text='Link to the drive folder for storing assignment related materials', null=True),
        ),
    ]
