# Generated by Django 5.2 on 2026-08-16 19:55

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0062_articlepage_assignment_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField(blank=True, help_text='The targeted deadline for this deliverable.', null=True, verbose_name='Deadline')),
                ('completed', models.BooleanField(default=False, help_text='An indication as to whether the deliverable is completed')),
                ('article_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='article.articlepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='articledeadline',
            name='article_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_list', to='article.articlepage'),
        ),
    ]
