# Generated by Django 5.2 on 2026-08-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('article', '0064_articlepage_story_type'), ('article', '0065_alter_articlepage_story_type'), ('article', '0066_alter_articlepage_story_type')]

    dependencies = [
        ('article', '0063_articledeadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='story_type',
            field=models.CharField(blank=True, choices=[('report', 'Report'), ('live-update', 'Live Update'), ('feature', 'Feature'), ('profile', 'Profile'), ('qa', 'Q&A'), ('review', 'Review'), ('game-analysis', 'Game Analysis'), ('commentary', 'Commentary'), ('essay', 'Essay'), ('column', 'Column'), ('editorial', 'Editorial'), ('letter-to-editor', 'Letter to the editor'), ('letter-from-editor', 'Letter from the editor'), ('psa', 'Public Service Announcement'), ('other', 'Other (this is an illegal option)')], max_length=255),
        ),
    ]
