# Generated by Django 5.2 on 2026-09-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0069_standardarticlepage_extended_byline_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='story_type',
            field=models.CharField(blank=True, choices=[('report', 'Report'), ('live-update', 'Live Update'), ('feature', 'Feature'), ('profile', 'Profile'), ('qa', 'Q&A'), ('review', 'Review'), ('game-analysis', 'Game Analysis'), ('commentary', 'Commentary'), ('essay', 'Essay'), ('column', 'Column'), ('editorial', 'Editorial'), ('letter-to-editor', 'Letter to the editor'), ('letter-from-editor', 'Letter from the editor'), ('psa', 'Public Service Announcement'), ('other', 'Other (requires Senior Masthead approval)')], max_length=255),
        ),
    ]
