# Generated by Django 5.2 on 2026-09-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0071_articlepage_covered_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='covered_sport',
            field=models.CharField(blank=True, choices=[('basketball-w', 'Basketball (W)'), ('basketball-m', 'Basketball (M)'), ('football', 'Football'), ('hockey-w', 'Hockey (W)'), ('hockey-m', 'Hockey (M)'), ('soccer-w', 'Soccer (W)'), ('soccer-m', 'Soccer (M)'), ('rugby-w', 'Rugby (W)'), ('volleyball-w', 'Volleyball (W)'), ('volleyball-m', 'Volleyball (M)')], default='', help_text='Required for game analyses shown in a sport-specific homepage filter.', max_length=20, verbose_name='Sport'),
        ),
    ]
