# Generated by Django 3.2.5 on 2021-08-23 23:51

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('specialfeaturelanding', '0003_alter_speciallandingpage_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciallandingpage',
            name='content',
            field=wagtail.fields.StreamField([('quote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.RichTextBlock(required=False)), ('source', wagtail.blocks.CharBlock(max_length=255, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('template', wagtail.blocks.ChoiceBlock(choices=[('guide-2020', '"Guide 2020"-Style Panel Quote')]))], label='Quote Block')), ('stylecta', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('content', wagtail.blocks.RichTextBlock(required=True)), ('link', wagtail.blocks.PageChooserBlock(required=True)), ('link_text', wagtail.blocks.CharBlock(max_length=255, required=True)), ('class_name', wagtail.blocks.CharBlock(max_length=255, required=True)), ('template', wagtail.blocks.ChoiceBlock(choices=[('guide-2020', '"Guide 2020"-Style CTA')]))], label='Custom Styling CTA'))], blank=True, null=True),
        ),
    ]
