# Generated by Django 3.2.11 on 2023-03-02 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbtemplates', '0001_initial'),
        ('specialfeaturelanding', '0017_alter_speciallandingpage_editorial_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciallandingpage',
            name='db_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dbtemplates.template'),
        ),
        migrations.AddField(
            model_name='speciallandingpage',
            name='layout',
            field=models.CharField(default='default', help_text='These correspond to very frequently used templates. More "bespoke", one-off templates should be added to the library of DB Templates', max_length=100, verbose_name='Article Layout'),
        ),
        migrations.AddField(
            model_name='speciallandingpage',
            name='use_default_template',
            field=models.BooleanField(default=True),
        ),
    ]
