# Generated by Django 3.2.11 on 2023-07-12 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_sectionpage_use_parent_colour'),
        ('specialfeaturelanding', '0019_alter_speciallandingpage_editorial_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciallandingpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.categorysnippet'),
        ),
    ]
