# Generated by Django 4.2 on 2025-02-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0019_alter_sectionpage_sidebar_stream'),
        ('specialfeaturelanding', '0031_alter_speciallandingpage_editorial_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciallandingpage',
            name='category',
        ),
        migrations.AddField(
            model_name='speciallandingpage',
            name='category_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='section.categorypage'),
        ),
    ]
