# Generated by Django 5.2 on 2026-10-04 23:16

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialfeaturelanding', '0040_redesignteammember_email_override'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redesigncontactentry',
            options={'verbose_name': 'Contact-only directory entry', 'verbose_name_plural': 'Contact-only directory entries'},
        ),
        migrations.AlterModelOptions(
            name='redesignteammember',
            options={'verbose_name': 'Our Team member', 'verbose_name_plural': 'Our Team members'},
        ),
        migrations.AlterField(
            model_name='redesignauxiliarypage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, default='', help_text='Optional introductory copy displayed below the page title.'),
        ),
        migrations.AlterField(
            model_name='redesigncontactentry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='redesignteammember',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
