# Generated by Django 3.2.11 on 2023-06-14 10:56

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('current_section', models.CharField(blank=True, default='', max_length=255)),
                ('use_parent_colour', models.BooleanField(default=True)),
                ('colour', wagtail_color_panel.fields.ColorField(default='#3490d6', max_length=7)),
                ('apply_colour_to_subtree_when_saved', models.BooleanField(default=False)),
                ('lock_colour', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Subsection',
                'verbose_name_plural': 'Subsections',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
    ]
