# Generated by Django 3.2.11 on 2023-08-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_ubysseyimage_legacy_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubysseyimage',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40),
        ),
    ]
