# Generated by Django 4.1 on 2024-07-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_ubysseyimage_file_alter_ubysseyrendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubysseyimage',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
