# Generated by Django 4.2 on 2024-08-17 06:51

from django.db import migrations
import wagtail.images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_ubysseyimage_file_alter_ubysseyrendition_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubysseyrendition',
            name='file',
            field=wagtail.images.models.WagtailImageField(height_field='height', storage=wagtail.images.models.get_rendition_storage, upload_to=wagtail.images.models.get_rendition_upload_to, width_field='width'),
        ),
    ]
