# Generated by Django 4.2 on 2025-03-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_ubysseyrendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubysseyimage',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
