# Generated by Django 4.2 on 2025-02-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_ubysseyrendition_file'),
        ('images', '0006_ubysseyimage_description'),
    ]

    operations = [
    ]
