# Generated by Django 5.2 on 2026-06-05 20:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_ubysseyimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubysseyimage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, default=''),
        ),
    ]
