# Generated by Django 3.2.11 on 2022-04-19 02:55

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210826_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='sections_stream',
            field=wagtail.core.fields.StreamField([('home_page_featured_section_block', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.PageChooserBlock(page_type=['section.SectionPage']))])), ('home_page_section_block', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.PageChooserBlock(page_type=['section.SectionPage']))]))], blank=True, null=True),
        ),
    ]
