# Generated by Django 3.2.11 on 2023-05-19 09:05

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_articlepage_noindex'),
        ('home', '0012_alter_homepage_sidebar_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cover_story',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_story', to='article.articlepage'),
        ),
    ]
