# Generated by Django 3.2.11 on 2023-05-23 20:56

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20230519_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='links',
            field=wagtail.core.fields.StreamField([('link', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=255, required=True)), ('url', wagtail.core.blocks.URLBlock(required=False)), ('description', wagtail.core.blocks.TextBlock(required=False))]))], blank=True, null=True),
        ),
    ]
