# Generated by Django 3.2.11 on 2023-06-27 02:32

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_alter_articlepage_content'),
        ('home', '0017_homepage_tagline_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cover_story',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_story', to='article.articlepage'),
        ),
    ]
