# Generated by Django 3.2.11 on 2023-07-18 18:39

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_homepage_cover_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sections_stream',
            field=wagtail.fields.StreamField([('home_page_section_block', wagtail.blocks.StructBlock([('section', wagtail.blocks.PageChooserBlock(page_type=['section.SectionPage'])), ('layout', wagtail.blocks.ChoiceBlock(choices=[('news', '"News Section" Style'), ('featured', '"Featured Section" Style')]))]))], blank=True, null=True),
        ),
    ]
