# Generated by Django 3.2.11 on 2023-08-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_homepage_cover_story'),
        ('home', '0023_alter_homepage_sidebar_stream'),
    ]

    operations = [
    ]
