# Generated by Django 4.2 on 2025-02-18 10:18

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_homepage_middle_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='middle_stream',
            field=wagtail.fields.StreamField([('links', wagtail.blocks.StructBlock([('links', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('url', wagtail.blocks.URLBlock(required=False)), ('description', wagtail.blocks.TextBlock(required=False))])))])), ('article_gatherer', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('section/objects/section_bulleted.html', 'Default'), ('section/objects/section_timeline.html', 'Timeline'), ('section/objects/section_horizontal.html', 'Horizontal'), ('section/objects/section_landing.html', 'Landing'), ('section/objects/minimal_grid.html', 'Minimal grid'), ('section/objects/blurb_with_timeline.html', 'Blurb with timeline'), ('section/objects/single_promo.html', 'Single (promo)'), ('section/objects/single_top-headline.html', 'Single (top headline)'), ('section/objects/single_top-headline_timeline.html', 'Single (top headline with timeline)')])), ('title', wagtail.blocks.CharBlock(help_text='Fill in to overwrite title', max_length=255, required=False)), ('description', wagtail.blocks.RichTextBlock(help_text='Fill in to overwrite description', required=False)), ('section', wagtail.blocks.PageChooserBlock(page_type=['section.SectionPage'], required=False)), ('category', wagtail.blocks.PageChooserBlock(page_type=['section.CategoryPage'], required=False)), ('tag_slug', wagtail.blocks.CharBlock(help_text="Enter tag slug. For example for 'Christmas Movie' the slug would be 'christmas-movie'.", required=False)), ('hide_mobile', wagtail.blocks.BooleanBlock(default=False, help_text='If checked, will hide on small devices', required=False))])), ('landing', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('section/objects/section_bulleted.html', 'Default'), ('section/objects/section_timeline.html', 'Timeline'), ('section/objects/section_horizontal.html', 'Horizontal'), ('section/objects/section_landing.html', 'Landing'), ('section/objects/minimal_grid.html', 'Minimal grid'), ('section/objects/blurb_with_timeline.html', 'Blurb with timeline'), ('section/objects/single_promo.html', 'Single (promo)'), ('section/objects/single_top-headline.html', 'Single (top headline)'), ('section/objects/single_top-headline_timeline.html', 'Single (top headline with timeline)')])), ('landing', wagtail.blocks.PageChooserBlock(page_type=['specialfeaturelanding.SpecialLandingPage']))])), ('article_manual', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('section/objects/section_bulleted.html', 'Default'), ('section/objects/section_timeline.html', 'Timeline'), ('section/objects/section_horizontal.html', 'Horizontal'), ('section/objects/section_landing.html', 'Landing'), ('section/objects/minimal_grid.html', 'Minimal grid'), ('section/objects/blurb_with_timeline.html', 'Blurb with timeline'), ('section/objects/single_promo.html', 'Single (promo)'), ('section/objects/single_top-headline.html', 'Single (top headline)'), ('section/objects/single_top-headline_timeline.html', 'Single (top headline with timeline)')])), ('title', wagtail.blocks.CharBlock(max_length=255, required=False)), ('description', wagtail.blocks.RichTextBlock(required=False)), ('link', wagtail.blocks.URLBlock(required=False)), ('articles', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(page_type=['article.ArticlePage']), required=False))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='top_stories_timeout',
            field=models.DateTimeField(blank=True, help_text="Before this date the manually set top stories list will be displayed. After this date the top stories list will be the 5 most recent articles tagged with 'Top stories'. Each section is limited to two articles. Only articles published in the last 2 weeks are included.", null=True, verbose_name='Top stories timeout'),
        ),
    ]
