# Generated by Django 4.2 on 2025-02-21 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_homepage_middle_stream_and_more'),
        ('home', '0030_alter_homepage_sidebar_stream'),
    ]

    operations = [
    ]
