# Generated by Django 4.2 on 2025-06-03 11:11

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_homepage_middle_stream_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='sections_stream',
            field=wagtail.fields.StreamField([('home_page_section_block', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('section/objects/section_one-large-two-small.html', 'One left, two right'), ('section/objects/section_article-row.html', 'Four articles in a row')])), ('section', wagtail.blocks.PageChooserBlock(page_type=['section.SectionPage'], required=True))])), ('home_page_section_block_categorized', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('section/objects/section_article-row--categorized.html', 'Grouped by categories')])), ('section', wagtail.blocks.PageChooserBlock(page_type=['section.SectionPage'], required=True)), ('fill_topic', wagtail.blocks.CharBlock(required=False)), ('columns', wagtail.blocks.StreamBlock([('single_category', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('section/objects/section_row_block.html', 'Grouped by categories')])), ('category', wagtail.blocks.PageChooserBlock('section.CategoryPage')), ('show_bylines', wagtail.blocks.BooleanBlock(required=False))])), ('multi_category', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('section/objects/section_row_block.html', 'Grouped by categories')])), ('title', wagtail.blocks.CharBlock(required=True)), ('categories', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock('section.CategoryPage'))), ('show_bylines', wagtail.blocks.BooleanBlock(required=False))]))], required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
