# Generated by Django 4.2 on 2025-08-11 10:02

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_homepage_middle_stream_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='curated_stream',
            field=wagtail.fields.StreamField([('curated_group', wagtail.blocks.StructBlock([('headline', wagtail.blocks.StreamBlock([('normal_headline', wagtail.blocks.StructBlock([('headline', wagtail.blocks.CharBlock()), ('style', wagtail.blocks.ChoiceBlock(choices=[('small', 'Small'), ('large', 'Large')])), ('link', wagtail.blocks.URLBlock(required=False))]))], max_num=1, required=False)), ('items', wagtail.blocks.StreamBlock([('storystream_item', wagtail.blocks.StructBlock([('article', wagtail.blocks.PageChooserBlock(page_type=['article.ArticlePage']))]))]))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sidebar_stream',
            field=wagtail.fields.StreamField([('sidebar_advertisement_block', wagtail.blocks.StructBlock([])), ('sidebar_issues_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('issues', wagtail.blocks.StreamBlock([('issue', wagtail.blocks.StructBlock([('date', wagtail.blocks.DateBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('show_image', wagtail.blocks.BooleanBlock(required=False)), ('link', wagtail.blocks.URLBlock(required=True))]))]))])), ('sidebar_flex_stream_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=True)), ('stream', wagtail.blocks.StreamBlock([('image_link', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('link', wagtail.blocks.URLBlock(required=False)), ('alt_text', wagtail.blocks.CharBlock(help_text='For accessibility to screen reader users, enter a description of this image. Included any relevant text inside the image.', max_length=255))]))]))])), ('sidebar_gatherer_block', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('infinitefeed/sidebar/sidebar_section_block.html', 'Default'), ('infinitefeed/sidebar/sidebar_latest_block.html', 'Latest')])), ('title', wagtail.blocks.CharBlock(help_text='Fill in to overwrite title', max_length=255, required=False)), ('description', wagtail.blocks.RichTextBlock(help_text='Fill in to overwrite description', required=False)), ('section', wagtail.blocks.PageChooserBlock(page_type=['section.SectionPage'], required=False)), ('category', wagtail.blocks.PageChooserBlock(page_type=['section.CategoryPage'], required=False)), ('tag_slug', wagtail.blocks.CharBlock(help_text="Enter tag slug. For example for 'Christmas Movie' the slug would be 'christmas-movie'.", required=False)), ('hide_mobile', wagtail.blocks.BooleanBlock(default=False, help_text='If checked, will hide on small devices', required=False)), ('highlight_colour', wagtail.blocks.CharBlock(default='0071c9', help_text='Only applicable to some templates', max_length=6, required=False))])), ('sidebar_manual', wagtail.blocks.StructBlock([('template', wagtail.blocks.ChoiceBlock(choices=[('infinitefeed/sidebar/sidebar_section_block.html', 'Default'), ('infinitefeed/sidebar/sidebar_latest_block.html', 'Latest')])), ('title', wagtail.blocks.CharBlock(max_length=255, required=False)), ('description', wagtail.blocks.RichTextBlock(required=False)), ('link', wagtail.blocks.URLBlock(required=False)), ('articles', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(page_type=['article.ArticlePage']), required=False))])), ('siderbar_events_block', wagtail.blocks.StructBlock([])), ('sidebar_recent_stories', wagtail.blocks.StructBlock([])), ('sidebar_recent_stories__clustered', wagtail.blocks.StructBlock([]))], blank=True, null=True, use_json_field=True),
        ),
    ]
