# Generated by Django 5.2 on 2026-06-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_homepage_curated_stream'),
        ('home', '0039_alter_homepage_curated_stream_and_more'),
    ]

    operations = [
    ]
