# Generated by Django 5.2 on 2026-09-03 10:35

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_homepage_curated_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='game_analysis',
            field=wagtail.fields.StreamField([('panel', 13)], blank=True, block_lookup={0: ('wagtail.blocks.MultipleChoiceBlock', [], {'choices': [('basketball-w', 'Basketball (W)'), ('basketball-m', 'Basketball (M)'), ('football', 'Football'), ('hockey-w', 'Hockey (W)'), ('hockey-m', 'Hockey (M)'), ('soccer-w', 'Soccer (W)'), ('soccer-m', 'Soccer (M)'), ('volleyball-w', 'Volleyball (W)'), ('volleyball-m', 'Volleyball (M)')], 'help_text': 'Sports shown in the homepage filter bar.', 'required': False}), 1: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['article.ArticlePage']}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('basketball-w', 'Basketball (W)'), ('basketball-m', 'Basketball (M)'), ('football', 'Football'), ('hockey-w', 'Hockey (W)'), ('hockey-m', 'Hockey (M)'), ('soccer-w', 'Soccer (W)'), ('soccer-m', 'Soccer (M)'), ('volleyball-w', 'Volleyball (W)'), ('volleyball-m', 'Volleyball (M)')]}), 3: ('wagtail.blocks.StructBlock', [[('article', 1), ('sport', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'max_num': 8, 'required': False}), 5: ('wagtail.blocks.DateTimeBlock', (), {'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 9: ('wagtail.blocks.IntegerBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('name', 7), ('icon', 8), ('score', 9)]], {}), 11: ('wagtail.blocks.StructBlock', [[('sport', 2), ('starts_at', 5), ('venue', 6), ('away_team', 10), ('home_team', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'max_num': 8, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('active_sports', 0), ('articles', 4), ('upcoming_games', 12), ('recent_results', 12)]], {})}, help_text='Homepage sports analysis stories, active sports, upcoming games and recent results.', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='newsletter_action_url',
            field=models.URLField(blank=True, default='', help_text='Mailchimp form action URL. Leave blank until the Mailchimp audience is configured; the preview form will remain disabled.'),
        ),
    ]
