# Generated by Django 5.2 on 2026-09-06

import wagtail.fields
from django.db import migrations


SPORT_CHOICES = [
    ("basketball-w", "Basketball (W)"),
    ("basketball-m", "Basketball (M)"),
    ("football", "Football"),
    ("hockey-w", "Hockey (W)"),
    ("hockey-m", "Hockey (M)"),
    ("soccer-w", "Soccer (W)"),
    ("soccer-m", "Soccer (M)"),
    ("rugby-w", "Rugby (W)"),
    ("volleyball-w", "Volleyball (W)"),
    ("volleyball-m", "Volleyball (M)"),
]


class Migration(migrations.Migration):
    dependencies = [("home", "0044_thunderbirdfixture")]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="game_analysis",
            field=wagtail.fields.StreamField(
                [("panel", 13)],
                blank=True,
                null=True,
                help_text="Homepage sports analysis stories, active sports, upcoming games and recent results.",
                block_lookup={
                    0: ("wagtail.blocks.MultipleChoiceBlock", [], {"choices": SPORT_CHOICES, "help_text": "Sports shown in the homepage filter bar.", "required": False}),
                    1: ("wagtail.blocks.PageChooserBlock", (), {"page_type": ["article.ArticlePage"]}),
                    2: ("wagtail.blocks.ChoiceBlock", [], {"choices": SPORT_CHOICES}),
                    3: ("wagtail.blocks.StructBlock", [[("article", 1), ("sport", 2)]], {}),
                    4: ("wagtail.blocks.ListBlock", (3,), {"max_num": 8, "required": False}),
                    5: ("wagtail.blocks.DateTimeBlock", (), {"required": False}),
                    6: ("wagtail.blocks.CharBlock", (), {"max_length": 120, "required": False}),
                    7: ("wagtail.blocks.CharBlock", (), {"max_length": 80}),
                    8: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                    9: ("wagtail.blocks.IntegerBlock", (), {"required": False}),
                    10: ("wagtail.blocks.StructBlock", [[("name", 7), ("icon", 8), ("score", 9)]], {}),
                    11: ("wagtail.blocks.StructBlock", [[("sport", 2), ("starts_at", 5), ("venue", 6), ("away_team", 10), ("home_team", 10)]], {}),
                    12: ("wagtail.blocks.ListBlock", (11,), {"max_num": 8, "required": False}),
                    13: ("wagtail.blocks.StructBlock", [[("active_sports", 0), ("articles", 4), ("upcoming_games", 12), ("recent_results", 12)]], {}),
                },
            ),
        )
    ]
