# Generated by Django 5.2 on 2026-09-07 04:03

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_homepage_redesign_cms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='game_analysis',
            field=wagtail.fields.StreamField([('panel', 14)], blank=True, block_lookup={0: ('wagtail.blocks.MultipleChoiceBlock', [], {'choices': [('basketball-w', 'Basketball (W)'), ('basketball-m', 'Basketball (M)'), ('football', 'Football'), ('hockey-w', 'Hockey (W)'), ('hockey-m', 'Hockey (M)'), ('soccer-w', 'Soccer (W)'), ('soccer-m', 'Soccer (M)'), ('rugby-w', 'Rugby (W)'), ('volleyball-w', 'Volleyball (W)'), ('volleyball-m', 'Volleyball (M)')], 'help_text': 'Sports shown in the homepage filter bar.', 'required': False}), 1: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['article.ArticlePage']}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('basketball-w', 'Basketball (W)'), ('basketball-m', 'Basketball (M)'), ('football', 'Football'), ('hockey-w', 'Hockey (W)'), ('hockey-m', 'Hockey (M)'), ('soccer-w', 'Soccer (W)'), ('soccer-m', 'Soccer (M)'), ('rugby-w', 'Rugby (W)'), ('volleyball-w', 'Volleyball (W)'), ('volleyball-m', 'Volleyball (M)')], 'help_text': "Legacy fallback. The article's Sport metadata is used when available.", 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('article', 1), ('sport', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('basketball-w', 'Basketball (W)'), ('basketball-m', 'Basketball (M)'), ('football', 'Football'), ('hockey-w', 'Hockey (W)'), ('hockey-m', 'Hockey (M)'), ('soccer-w', 'Soccer (W)'), ('soccer-m', 'Soccer (M)'), ('rugby-w', 'Rugby (W)'), ('volleyball-w', 'Volleyball (W)'), ('volleyball-m', 'Volleyball (M)')]}), 6: ('wagtail.blocks.DateTimeBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 10: ('wagtail.blocks.IntegerBlock', (), {'required': False}), 11: ('wagtail.blocks.StructBlock', [[('name', 8), ('icon', 9), ('score', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('sport', 5), ('starts_at', 6), ('venue', 7), ('away_team', 11), ('home_team', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'max_num': 8, 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('active_sports', 0), ('articles', 4), ('upcoming_games', 13), ('recent_results', 13)]], {})}, help_text='Homepage sports analysis stories, active sports, upcoming games and recent results.', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='newsletter_honeypot_name',
            field=models.CharField(blank=True, default='', help_text='Only change this with the matching anti-bot field supplied by the newsletter provider.', max_length=160),
        ),
        migrations.AlterField(
            model_name='homepageredesignstory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='thunderbirdfixture',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
