# Generated by Django 5.2 on 2026-09-17 22:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_named_homepage_hero_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='game_analysis',
            field=wagtail.fields.StreamField([('panel', 5)], blank=True, block_lookup={0: ('wagtail.blocks.MultipleChoiceBlock', [], {'choices': [('basketball-w', 'Basketball (W)'), ('basketball-m', 'Basketball (M)'), ('football', 'Football'), ('hockey-w', 'Hockey (W)'), ('hockey-m', 'Hockey (M)'), ('soccer-w', 'Soccer (W)'), ('soccer-m', 'Soccer (M)'), ('volleyball-w', 'Volleyball (W)'), ('volleyball-m', 'Volleyball (M)')], 'help_text': 'Sports shown in the homepage filter bar.', 'required': False}), 1: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['article.ArticlePage']}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('basketball-w', 'Basketball (W)'), ('basketball-m', 'Basketball (M)'), ('football', 'Football'), ('hockey-w', 'Hockey (W)'), ('hockey-m', 'Hockey (M)'), ('soccer-w', 'Soccer (W)'), ('soccer-m', 'Soccer (M)'), ('volleyball-w', 'Volleyball (W)'), ('volleyball-m', 'Volleyball (M)')], 'help_text': "Legacy fallback. The article's Sport metadata is used when available.", 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('article', 1), ('sport', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('active_sports', 0), ('articles', 4)]], {})}, help_text='Homepage sports analysis stories and active sports. Fixtures and scores are managed in Sports Calendar.', null=True),
        ),
    ]
