# Generated by Django 3.2.11 on 2023-07-10 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_magazinetagorderable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MagazineTagOrderable',
        ),
    ]
