# Generated by Django 3.2.11 on 2023-07-12 04:06

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('section', '0003_sectionpage_use_parent_colour'),
        ('archive', '0002_sectionpageorderables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpageorderables',
            name='section_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Section Page'),
        ),
        migrations.CreateModel(
            name='MagazineOrderables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('magazine_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='section.categorysnippet', verbose_name='Magazine')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazines_filters', to='archive.archivepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
