# Generated by Django 3.2.11 on 2023-07-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('archive', '0003_delete_magazinetagorderable'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivepage',
            name='sections_filters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Page Link'),
        ),
    ]
