# Generated by Django 4.2 on 2025-02-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0019_alter_sectionpage_sidebar_stream'),
        ('archive', '0004_spooforderables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazineorderables',
            name='magazine_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='section.categorypage', verbose_name='Magazine'),
        ),
        migrations.AlterField(
            model_name='spooforderables',
            name='spoof_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='section.categorypage', verbose_name='Spoof'),
        ),
    ]
