# Generated by Django 3.2.11 on 2023-07-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_auto_20230710_0413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionpageorderables',
            old_name='sections_filters',
            new_name='section_filter',
        ),
    ]
