# Generated by Django 5.2 on 2026-08-19 21:51

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossword',
            name='puzzle',
            field=wagtail.fields.StreamField([('across', 1), ('down', 3)], block_lookup={0: ('wagtail.blocks.StructBlock', [[]], {'answer': models.CharField(max_length=100), 'clue': models.CharField(max_length=100), 'column': models.IntegerField(), 'row': models.IntegerField()}), 1: ('wagtail.blocks.ListBlock', (0,), {}), 2: ('wagtail.blocks.StructBlock', [[]], {'answer': models.CharField(max_length=100), 'clue': models.CharField(max_length=100), 'column': models.IntegerField(), 'row': models.IntegerField()}), 3: ('wagtail.blocks.ListBlock', (2,), {})}, null=True),
        ),
    ]
