# Generated by Django 5.2 on 2026-08-19 21:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_crossword_puzzle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossword',
            name='puzzle',
            field=wagtail.fields.StreamField([('across', 3), ('down', 3)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.IntegerBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('clue', 0), ('answer', 0), ('row', 1), ('column', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {})}, null=True),
        ),
    ]
