# Generated by Django 5.2 on 2026-08-15 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stove', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManuscriptCollaboration',
            new_name='PageCollaboration',
        ),
    ]
