name: Deploy to staging

# on:
#   release:
#     types: [published]

on:
  push:
    branches:
      - staging-deploy

jobs:
  deploy:

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14.x'

      - run: |
          npm install
          npm install -g gulp
          npm rebuild node-sass
          gulp build
        working-directory: ubyssey/static_src
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt

      - name: Collect Django static files
        run: DJANGO_SETTINGS_MODULE=config.settings.base python manage.py collectstatic --noinput

      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/1012602718138/locations/global/workloadIdentityPools/ubyssey-wif-pool-staging/providers/ubyssey-oidc-github-staging'
          service_account: 'deployment@ubyssey-staging.iam.gserviceaccount.com'

      - uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'static'
          destination: 'ubyssey-staging'

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: deploy
          SSH_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY_STAGING }}
          SSH_HOST: ${{ secrets.GCP_SSH_HOST_STAGING }}

      - name: Set tag in docker-compose.yml
        run: sed -i "s/\${TAG}/${{ github.ref_name }}/g" docker-compose.yml

      - name: Upload Docker Compose configuration
        run: scp docker-compose.yml staging:/opt/ubyssey.ca/docker-compose.yml

      - name: Upload nginx configuration
        run: scp -r nginx staging:/opt/ubyssey.ca/nginx
        
      - name: Restart services
        run: ssh staging << EOF
          export $(gcloud secrets versions access latest --secret="ubyssey_env_configs" | xargs)
          docker compose -f /opt/ubyssey.ca/docker-compose.yml -p ubyssey up -d
          EOF
