name: Deploy to production

on:
  release:
    types: [published]

jobs:
  deploy:

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14.x'

      - run: |
          npm install
          npm install -g gulp
          npm rebuild node-sass
          gulp build
        working-directory: ubyssey/static_src
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt

      - name: Collect Django static files
        run: DJANGO_SETTINGS_MODULE=config.settings.base python manage.py collectstatic --noinput

      - name: Authenticate with Google Cloud Platform
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/863738545301/locations/global/workloadIdentityPools/ubyssey-wif-pool-prd/providers/ubyssey-oidc-github-prd'
          service_account: 'deployment@ubyssey-prd.iam.gserviceaccount.com'

      - name: Upload static files to Google Cloud Storage
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'static'
          destination: 'ubyssey'

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: deploy-production
          SSH_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY_PRODUCTION }}
          SSH_HOST: ${{ secrets.GCP_SSH_HOST_PRODUCTION }}

      - name: Set tag in docker-compose.yml
        run: sed -i "s/\${TAG}/${{ github.ref_name }}/g" docker-compose.yml

      - name: Upload Docker Compose configuration
        run: scp docker-compose.yml production:/opt/ubyssey.ca/docker-compose.yml

      - name: Upload nginx configuration
        run: scp nginx.conf production:/opt/ubyssey.ca/nginx/nginx.conf
        
      - name: Sync secrets from Google Cloud Platform
        run: cat sync-secrets.sh | ssh production

      - name: Restart services
        run: ssh production docker stack deploy --compose-file /opt/ubyssey.ca/docker-compose.yml ubyssey
