on:
  push:
    branches: [ "add-a-CI/CD-pipeline" ]
  pull_request:
    branches: [ "add-a-CI/CD-pipeline" ]
    
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: | 
            cd ubyssey-dev/.devcontainer
            docker compose build
            docker compose run --rm web python manage.py test