on:
  push:
    branches: [ "add-a-CI/CD-pipeline" ]
  pull_request:
    branches: [ "add-a-CI/CD-pipeline" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: | 
            cd ubyssey-dev/.devcontainer
            cat docker-compose.yml